### PR TITLE
Main

### PR DESCRIPTION
**Pull request by jacobo12montes**
-Create main layout
-Give each element size and position
-Put the images as the background on the elements
-Give the style to the navbar of the page
-Give the style to the footer

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @jacobo12montes 
### You have done a good job so far :clap: However, you have a few issues that need to be solved.
- Solve lint issues highlighted in the pull request
- Practise using html5 tags, like in the nav section, you can use unordered list and list items instead of the divisions
navbar
- In the 4 image thumbnails, add space in between
- Add some space in your footer elements and make them aligned as from the original design
footer
### Make those changes and resubmit for another code review. Good luck.
- Happy coding!

**Comment by jacobo12montes** [comment]
Hi @rOluochKe can you explain me with more details what are the problems with the lint issue ? thanks

**Comment by jacobo12montes** [comment]
The changes requested were executed.

**Review by christianotieno — CHANGES_REQUESTED** [review]
## Good job implementing the required changes @jacobo12montes! 👍 
We are almost there, we just forgot to pass our markup through a validator to remove any error or warning, kindly let's do that and submit for another code review, thanks. 
- Use this [tool](https://validator.w3.org/nu/#textarea).

Cheers 💯 

[Christian Otieno](https://github.com/christianotieno)

**Comment by jacobo12montes** [comment]
fix the errors on the html validator

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project @jacobo12montes. :fireworks:  Keep it up.
##
### The [clone](https://raw.githack.com/jacobo12montes/Apple/main/index.html) shows good understanding and usage of building with background gradients. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
-  The project has a descriptive README.md and is professionally done. Good job with that but please, improve on the documentation on how to clone the repo. The link is redirecting the user elsewhere.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @jacobo12montes! :+1:
- Make that one change in the README and then merge to master. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Pull request merged**
